server:
  port: 8803


spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的 rabbitmq 的服务信息
        defaultRabbit: # 表示定义的名称，用户binding 整合
          type: rabbit # 消息组件类型
          environment: # 设置 rabbit mq 的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的 Exchange 名称定义
          content-type: application/json # 设置消息类型，本次为json, 文本则设置为 “text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: suguanzhou  # 增加分组设置，解决重复消费和消息丢失没有持久化问题

eureka:
  client:
    fetch-registry: true # 表示是否将自己注册进eureka ， 默认为true
    register-with-eureka: true # 是否从 eurekaServer 抓取已有的注册信息，默认为true, 单节点无所谓，集群必须设置为true才能配合 ribbon 使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: receive-8802.com
    prefer-ip-address: true  # eureka 上显示IP